### ISSUE TITLE
QQ群还可以➕我进去吗？

### ISSUE THREAD

**Issue by derboys** [dakuohao/GetDouYin#1]
你好，群主，我想进群和大家一起交流爬虫技术。望通过

**Comment by kingkf** [comment]
同想加, 747939602

**Comment by MrXCQ** [comment]
1044897034 群主麻烦拉一下，交流技术

**Comment by dakuohao** [comment]
点击链接加入群聊【数据爬取技术群】：https://jq.qq.com/?_wv=1027&k=5SzYVhQ
